[fix] Add card buttons to list grids
woody-wordpress/woody-theme pull request #268
Opened 2021-11-09 11:07 UTC by Anymfah

Permet d'afficher les boutons des cards en lists grids.

2021-11-15 16:51 UTC, benbchd requested changes
Dans le fichier class-woody-compilers.php, l.85 : 
            $the_items['display_button'] = (!empty($wrapper['display_button'])) ? $wrapper['display_button'] : false;
Cela permet d'ajouter le bouton autant pour getAutoFocusData que pour getManualFocusData, getAutoFocusSheetData ou getAutoFocusTopicsData

Il vaut mieux ajouter cette ligne dans la fonction qui compile les listes de contenus

2021-11-19 08:01 UTC, benbchd commented
@Anymfah : ne pas oublier cette PR ;)

2021-11-26 09:19 UTC, Anymfah commented
Ok c'est bon

2021-11-26 09:50 UTC, benbchd commented
@Anymfah , on ne s'est pas compris dsl 
=> Tu traites l'affichage des boutons dans la fonction getAutofocusData, qui elle même est appelée par formatFocusesData => dans formatFocusesData on traite déjà le l'affichage des boutons pour les layouts manual_focus, focus_trip_components, auto_focus, auto_focus_sheets, auto_focus_topics et profile_focus. (cf class-woody-process l.43)
=> Les listes de contenus ne passent pas par la fonction formatFocusesData. (cf class-woody-process l.43)
=> Il faut ajouter le traitement du bouton dans la fonction qui gère les listes de contenus => formatListContent

2021-12-07 11:15 UTC, benbchd commented
@Anymfah : à corriger pour pouvoir passer en prod

2021-12-07 13:27 UTC, Anymfah commented
C'est bon je pense

2021-12-07 13:56 UTC, benbchd approved these changes

2021-12-07 13:56 UTC, merged