[func] Add Filter to add thumbnails paths
woody-wordpress/woody-theme pull request #271
Opened 2021-11-25 09:14 UTC by Anymfah

- Ajout d'un filtre pour passer le chemin des thumbnails depuis un addon.
- Affichage du bookblock

2021-11-26 12:42 UTC, benbchd requested changes

2021-11-26 12:42 UTC, benbchd commented on src/js/admin/woody-tpl.js
> +            button.parent().first('[data-name="woody_tpl"').find('input').val($('.tpl-choice-wrapper.selected').data('value'));
Cette modification est-elle vraiment nécessaire ? 
Le field key apporte une sécurité que le "first" n'apporte pas (template != woody_tpl ou ordre des champs différent).

2021-11-29 11:08 UTC, Anymfah commented on src/js/admin/woody-tpl.js
> +            button.parent().first('[data-name="woody_tpl"').find('input').val($('.tpl-choice-wrapper.selected').data('value'));
La modification a été apportée (rollback)

2021-11-30 16:08 UTC, benbchd approved these changes

2021-11-30 16:08 UTC, merged