[edit] Change character code
woody-wordpress/woody-theme pull request #275
Opened 2021-12-08 08:41 UTC by Anymfah

Le character "-" s'affichait avec le mauvais code dans certaines typos.

2021-12-17 15:50 UTC, benbchd requested changes

2021-12-17 15:50 UTC, benbchd commented on library/classes/process/class-woody-compilers.php
> +        $page_teaser['page_teaser_title'] = !empty($page_teaser['page_teaser_display_title']) ? $context['post_title'] : '';
De mémoire, on s'était dit de ne pas juste supprimer le replace mais passer par get_the_title($context['post_id]) pour passer par la fonction wp_texturize (à tester)

2022-01-12 07:40 UTC, benbchd commented on library/classes/process/class-woody-compilers.php
> +        $page_teaser['page_teaser_title'] = !empty($page_teaser['page_teaser_display_title']) ? $context['post_title'] : '';
Up @Anymfah

2022-02-10 09:08 UTC, benbchd commented on library/classes/process/class-woody-compilers.php
> +        $page_teaser['page_teaser_title'] = !empty($page_teaser['page_teaser_display_title']) ? $context['post_title'] : '';
re-up @Anymfah

2022-02-25 08:03 UTC, benbchd commented on library/classes/process/class-woody-compilers.php
> +        $page_teaser['page_teaser_title'] = !empty($page_teaser['page_teaser_display_title']) ? $context['post_title'] : '';
@Anymfah , est-ce que cette PR a toujours lieu d'être ? Sinon, je la supprime

2022-02-25 08:08 UTC, Anymfah commented on library/classes/process/class-woody-compilers.php
> +        $page_teaser['page_teaser_title'] = !empty($page_teaser['page_teaser_display_title']) ? $context['post_title'] : '';
Désolé pour cette PR. Je viens de tester et je ne rencontre plus le problème en tout cas donc on peut la fermer.

2022-02-25 08:19 UTC, closed without merging